fix

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,7 +5,6 @@ on:
       - main
 jobs:
   build:
-    name: Build the project
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -13,16 +12,20 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: '20'
-          
+
       - name: Install Dependencies
         run: |
-          echo "NODE_PATH=$NODE_PATH:$GITHUB_WORKSPACE/paytm_turbo" >> $GITHUB_ENV
+          echo "NODE_PATH=$NODE_PATH:$GITHUB_WORKSPACE" >> $GITHUB_ENV
           npm ci
         working-directory: paytm_turbo
 
       - name: Generate Prisma Client
         run: npm run db:generate
         working-directory: paytm_turbo  
+        
+      - name: Debug @repo/ui Dist
+        run: ls -la packages/ui/dist || echo "Dist folder not found yet"
+        working-directory: paytm_turbo
 
       - name: Run Build
         run: npm run build
